### PR TITLE
WIP: Aerolyzer_app-15 solr functionality

### PR DESCRIPTION
**Pull request by colliell**
WIP for implementing solr functionality. Search url works and image/gallery are showing up (i.e. http://127.0.0.1:8000/search/) but manage.py rebuild_index throws an error. Not sure if we need to create a core or if the indexes/text files in this PR are incorrect.

### CODE REVIEW

**Comment by kwhitehall** [comment]
Hi @colliell I'm unsure how to test this. There is no search option in the user profile e.g. under gallery, that a user can search - Assuming that this search functionality is for the front end stuff. Please provide more details on the functionality being supplied here. Also, please update the README here as well to provide guidance on what programs need to be running inorder to test this out.

**Comment by kwhitehall** [comment]
Also are these auto-generated files e.g. Aerolyzer/app/migrations/0002_auto_20170308_1423.py required in the PR? If they are, the end user has to run python manage.py migrate to 'update them'. It may be better to indicate in the README how to generate them, and avoid them in the codebase. Thoughts?

**Comment by colliell** [comment]
Currently Solr is integrated into Django with the config and schema provided in this PR.
The search page (http://127.0.0.1:8000/search when running locally) is from the haystack tutorial. I modified the url to require an admin login in order to access, allowing us to query the gallery and image tables. 

Steps taken that may need to be reproduced in production:

- Create the aerolyzer core with data directory "data" and instance directory "aerolyzer"
- Place provided schema.xml and solarconfig.xml files in the solr-5.5.4/server/solr/aerolyzer/conf directory 
- Start Solr on port 8983 (the default)
- Run manage.py update_index to update Solr data
[From Haystack tutorial: "You should cron up a ./manage.py update_index job at whatever interval works best	for your site (using --age=<num_hours> reduces the number of things to update).")]

~~Still a WIP because although the indexes seem to be working, when querying something on the search page the manage.py runserver output in the terminal gives an error:~~
```
Failed to query Solr using '(sdfadfsdfdsf)': Solr responded with an error (HTTP 400): [Reason: undefined field _text_]
Traceback (most recent call last):
  File "C:\Python271\lib\site-packages\haystack\backends\solr_backend.py", line 134, in search
    raw_results = self.conn.search(query_string, **search_kwargs)
  File "build\bdist.win32\egg\pysolr.py", line 720, in search
    response = self._select(params, handler=search_handler)
  File "build\bdist.win32\egg\pysolr.py", line 418, in _select
    return self._send_request('get', path)
  File "build\bdist.win32\egg\pysolr.py", line 393, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
SolrError: Solr responded with an error (HTTP 400): [Reason: undefined field _text_]
```

~~Not sure if this is due to something in the schema.xml or solrconfig.xml?~~

Fixed by restarting Solr and recreating core. The reason for the error was Solr hadn't been restarted and therefore wasn't using the correct schema.

**Comment by colliell** [comment]
@kwhitehall Solr should be integrated successfully with this PR

**Review by kwhitehall — APPROVED** [review]
Nice job cleaning up the PR @colliell  and addressing the bug. LGTM! Merge away! 
Next step will be getting this search page integrated on a user's profile (on the Gallery page for e.g.)

**Pull request merged**
